import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="px-5 py-2 flex justify-between gap-5 bg-stone-800">
          {/* logo */}
          <div className="text-xl text-orange-400">Foods</div>
          {/* nav */}
          <nav>
            <ul className="flex gap-5 text-white">
              <li><Link href="/">Home</Link></li>
              <li><Link href="/foods" prefetch={false}>All Foods</Link></li>
              <li><Link href="/reviews">Reviews</Link></li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
